<?php

$calenders = array(
	"graduated" => array("lisansüstü\nlisansüstü"),
	"undergraduate" => array("<h4>YURT DIŞI KONTENJANINDAN ÖĞRENCİ ALIMI, ÖZEL YETENEK SINAVI, YATAY GEÇİŞ, ÇİFT ANADAL VE YANDAL İÇİN BAŞVURULAR</h4>",
								"<h5>Yurtdışı Kontenjanından Öğrenci Alımı Başvuruları</h5>",
								"Yurt Dışı Kontenjanından Öğrenci Alımı Kontenjanlarına Başvurular<br /><i>05 Haziran 2015 - 31 Temmuz 2015",
								"<h5>Özel Yetenek Sınavı (ÖSYS Puanına Göre) İle Öğrenci Alan Programlar İçin Başvurular</h5>",
								"Türk Musikisi Devlet Konservatuvarı Özel Yetenek Programı İçin Başvuruları<br /><i>1 Temmuz 2015 - 24 Temmuz 2015",
								"<h5>Yatay Geçiş İçin Başvurular</h5>",
								"Kurum İçi ve Kurumlararası Yatay Geçiş Kontenjanlara Başvurular<br /><i>03 Ağustos 2015 - 14 Ağustos 2015",
								"Yatay Geçiş Başvurularının Değerlendirilmesinin Sonuçlandırılması<br /><i>17 Ağustos 2015 - 27 Ağustos 2015",
								"Yatay Geçiş Sonuçlarının Web Sayfasında İlanı<br /><i>28 Ağustos 2015",
								"Kayıt Hakkı Kazanan Adayların Kesin Kayıt Tarihi, Katkı Payı/Öğrenim Ücreti Ödemesi İşlemler<br /><i>31 Ağustos 2015 - 04 Eylül 2015",
								"Boş Kontenjanların ve Yedek Listesinin Web Sayfasında İlanı<br /><i>07 Eylül 2015",
								"Yedekten Kayıt Hakkı Kazananların Kesin Kayıt Tarihi, Katkı Payı/Öğrenim Ücreti Ödemesi İşlemleri<br /><i>16 Eylül 2015 - 18 Eylül 2015",
								"<h5>Ek Madde-1 Kapsamında Merkezi Yerleştirme Puanı ile Yatay Geçiş İçin Başvurular</h5>",
								"Yatay Geçiş Kontenjanlara Başvuruları<br /><i>17 Ağustos 2015 - 28 Ağustos 2015",
								"Yatay Geçiş Başvurularının Değerlendirilmesinin Sonuçlandırılması<br /><i>31 Ağustos 2015 - 11 Eylül 2015",
								"Yatay Geçiş Sonuçlarının Web Sayfasında İlanı<br /><i>15 Eylül 2015",
								"Kayıt Hakkı Kazanan Adayların Kesin Kayıt Tarihi, Katkı Payı/Öğrenim Ücreti Ödemesi İşlemleri<br /><i>16 Eylül 2015 - 18 Eylül 2015",
								"<h5>Ek Madde-2 Kapsamında Suriye, Mısır ve Yemen Üniversitelerinden Yatay Geçiş İçin Başvurular</h5>",
								"Yatay Geçiş Kontenjanlara Başvuruları<br /><i>17 Ağustos 2015 - 28 Ağustos 2015",
								"Yatay Geçiş Başvurularının Değerlendirilmesinin Sonuçlandırılması<br /><i>31 Ağustos 2015 - 11 Eylül 2015",
								"Yatay Geçiş Sonuçlarının Web Sayfasında İlanı<br /><i>15 Eylül 2015",
								"Kayıt Hakkı Kazanan Adayların Kesin Kayıt Tarihi, Katkı Payı/Öğrenim Ücreti Ödemesi İşlemleri<br /><i>16 Eylül 2015 - 18 Eylül 2015",
								"<h5>Çift Anadal ve Yandal Programları İçin Başvurular</h5>",
								"Çift Anadal / Yandal Kontenjanı Açılan Programların İlanı İçin Son Gün<br /><i>14 Ağustos 2015",
								"Çift Anadal / Yandal Kontenjanları İçin Başvuruları<br /><i>17 Ağustos 2015 - 21 Ağustos 2015",
								"Başvuru Sonuçlarının Web Sayfasında İlan Edilmesi İçin Son Gün<br /><i>04 Eylül 2015",
								"Kayıt Hakkı Kazanan Adayların Kesin Kayıt Tarihi Başlangıcı<br /><i>07 Eylül 2015 - 11 Eylül 2015",
								"<h4>YENİ ÖĞRENCİLERİN KAYITLARI<h4>",
								"<h5>ÖSYS, DGS, Türkiye Bursları ve Özel Yetenek Sınavı vb. İle Kayıt Hakkı Kazananların Kesin Kayıt Tarihleri</h5>",
								"Kesin Kayıtları<br /><i>03 Ağustos 2015 - 07 Ağustos 2015",
								"Ek Yerleştirme Kayıtları<br /><i>31 Ağustos 2015 - 04 Eylül 2015",
								"<h5>Yurtdışı Kontenjanından Kayıt Hakkı Kazananların Kesin Kayıt Tarihleri ve Oryantasyon Eğitimi</h5>",
								"Kesin Kayıtları<br /><i>24 Ağustos 2015 - 28 Ağustos 2015",
								"Ek Yerleştirme Kayıtları<br /><i>04 Eylül 2015 - 11 Eylül 2015",
								"Oryantasyon Eğitimi<br /><i>28 Eylül 2015 - 02 Ekim 2015",
								"<h5>İNGİLİZCE VE TÜRKÇE YETERLİLİK SINAVI</h5>",
								"Yabancı Dil Muafiyet Sınavı Tarihi<br /><i>14-15 Eylül 2015",
								"Türkçe Yeterlilik Sınavı Tarihi<br /><i>16 Eylül 2015",
								"<h4>KAYIT YENİLEME (DERS ALMA, DANIŞMAN ONAYI, DERS EKLEME/BIRAKMA VE KATKI PAYI/ÖĞRENİM ÜCRETİ YATIRMA) TARİHLER</h4>",
								"<h5>Yeni Kayıt Hakkı Kazanan Öğrenciler İçin</h5>",
								"Öğrenci Katkı Payı / Öğrenim Ücreti Ödeme Tarihleri (İkinci Öğretim öğrencileri için)<br /><i>03 Ağustos 2015 - 07 Ağustos 2015",
								"Öğrenci Otomasyon Sistemi Üzerinden Ders Alma İşlemleri<br /><i>14 Eylül 2015 - 20 Eylül 2015",
								"Öğrenci Otomasyon Sistemi Üzerinden Danışman Ders Onayı İşlemleri<br /><i>14 Eylül 2015 - 21 Eylül 2015",
								"<h5>Kayıtlı Öğrenciler İçin Güz ve Bahar Yarıyılı Kayıt Yenileme</h5>",
								"Öğrenci Katkı Payı / Öğrenim Ücreti Ödeme Tarihleri ( Kayıtlı Öğrenciler )<br /><i>14 Eylül 2015 - 20 Eylül 2015",
								"Öğrenci Otomasyon Sistemi Üzerinden Ders Alma İşlemleri<br /><i>14 Eylül 2015 - 20 Eylül 2015",
								"Öğrenci Otomasyon Sistemi Üzerinden Danışman Ders Onayı İşlemleri<br /><i>14 Eylül 2015 - 21 Eylül 2015",
								"Öğrenci Otomasyon Sistemi Üzerinden Ders Ekleme/Bırakma İşlemleri<br /><i>28 Eylül 2015 - 09 Ekim 2015",
								"Öğrenci Otomasyon Sistemi Üzerinden Danışman Ders Ekleme/Bırakma Onayı İşlemleri<br /><i>28 Eylül 2015 - 11 Ekim 2015",
								"Çift Anadal/Yandal Programlarına İlk Defa Kayıt Yaptıracak Adayların Ders Alma İşlemleri<br /><i>14 Eylül 2015 - 20 Eylül 2015",
								"Çift  Anadal/Yandal Programlarına  İlk  Defa  Kayıt  Yaptıracak Adayların Danışman Ders Alma Onay İşlemleri<br /><i>14 Eylül 2015 - 21 Eylül 2015",
								"<h4>GÜZ VE BAHAR YARIYILI EĞİTİM - ÖĞRETİM, YARIYIL SONU SINAVLARI, SINAV SONUÇLARI İLAN TARİHLERİ</h4>",
								"Eğitim – Öğretim Dönemi<br /><i>28 Eylül 2015 - 01 Ocak 2016",
								"Yeni Kayıt yaptıran öğrencilerin varsa ders muafiyet talebini ilgili dekanlığa bildirme süresi<br /><i>02 Ekim 2015",
								"Yeni Kayıt Öğrencilerinin Muafiyet Talepleri Sonucunda Muaf Olduğu Derslerin Ders Alma Listesinden Kaldırılması ve Muafiyetlerinin Öğrenci Otomasyon Sistemine İşlenmesi<br /><i>16 Ekim 2015",
								"Yarıyıl/Yıl Dönem Sonu ve Bütünleme Sınav Tarihlerinin İlgili Fakülte Web Sayfasında İlanı İçin Son Gün<br /><i>18 Aralık 2015",
								"Yarıyıl/Yıl Sonu Sınavları<br /><i>04 Ocak 2016 - 17 Ocak 2016",
								"Öğrenci Otomasyon Sistemine Yarıyıl Sonu Not Girişleri<br /><i>İlgili dersin sınav tarihi - İlgili dersin sınav tarihinden itibaren 5 (beş) gün",
								"Yarıyıl / Yıl Sonu Bütünleme Sınavları<br /><i>25 Ocak 2016 - 05 Şubat 2016",
								"Öğrenci Otomasyon Sistemine Yarıyıl / Yıl Sonu Bütünleme Sınavları Not Girişleri<br /><i>İlgili dersin sınav tarihi - İlgili dersin sınav tarihinden itibaren 5 (beş) gün",
								"Ek Sınav Tarihleri (Son Dönem Öğrencileri için)<br /><i>09 Şubat 2016 - 11 Şubat 2016"
						),
	"ydyo" => array("ydyo\nydyo"),
	"medicine" => array("medicine\nmedicine")
);
echo json_encode($calenders);
